version: '3.7'

services:

  oncare:
    container_name: ipd-analysis
    build:
      context: .
      dockerfile: Dockerfile
    image: ipd_analysis_container

    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 9000:9000
    environment:
      - CHOKIDAR_USEPOLLING=true